# Generated by Django 4.2 on 2023-04-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('country', models.CharField(max_length=100)),
                ('purchase_date', models.IntegerField()),
            ],
        ),
    ]
