# Generated by Django 4.2 on 2023-04-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.CharField(default='Nike', max_length=100)),
                ('price', models.IntegerField(default=99)),
                ('fee', models.IntegerField(default=5)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('country', models.CharField(default='usa', max_length=100)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
    ]
